[package]
name = "tc_noekeon_v2"
description = "Noekeon single-block encryption in direct-key mode."
version.workspace = true
edition.workspace = true
rust-version = "1.85"
license.workspace = true
repository.workspace = true

[dependencies]
tc_block_cipher = { path = "../tc_block_cipher" }
tc_zeroize = "0.1.0"
