[package]
name = "tc_aes_v2"
version.workspace = true
edition.workspace = true
rust-version = "1.85"
license.workspace = true
repository.workspace = true

[features]
rustcrypto = ["dep:aes", "aes/zeroize"]

[dependencies]
tc_block_cipher = { path = "../tc_block_cipher" }
tc_zeroize = "0.1.0"
aes = { version = "0.9.3", optional = true }