[package]
name = "tc_twofish_v2"
description = "Twofish single-block encryption with 128-, 192- and 256-bit keys."
version.workspace = true
edition.workspace = true
rust-version = "1.85"
license.workspace = true
repository.workspace = true

[dependencies]
tc_block_cipher = { path = "../tc_block_cipher" }
tc_zeroize = "0.1.0"

[dev-dependencies]
twofish = "0.8"
