[package]
name = "tc_f2m_custom"
description = "Per-field specialized SEC binary elliptic curves."
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tc_bigint = { version = "0.1.0", path = "../tc_bigint", default-features = false, features = ["alloc"] }
tc_binpoly = { version = "0.1.0", path = "../tc_binpoly", default-features = false }
tc_ec_core = { version = "0.1.0", path = "../tc_ec_core" }
tc_f2m_curve = { version = "0.1.0", path = "../tc_f2m_curve" }

[dev-dependencies]
tc_binpoly = { version = "0.1.0", path = "../tc_binpoly", default-features = false, features = ["alloc"] }

