[package]
name = "tc_cast_v2"
description = "CAST5 and CAST6 single-block cipher engines"
version.workspace = true
edition.workspace = true
rust-version = "1.85"
license.workspace = true
repository.workspace = true

[dependencies]
tc_block_cipher = { path = "../tc_block_cipher" }
tc_zeroize = "0.1.0"

[dev-dependencies]
cast5 = "0.12"
cast6 = "0.2"
