[package]
name = "tc_limb"
description = "Fixed-width little-endian limb arithmetic."
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tc_constant_time = { version = "0.1.0", path = "../tc_constant_time" }

[dev-dependencies]
num-bigint = "0.5.1"
