[package]
name = "tc_buff"
description = "Buffered cipher adapters for the tc_rust workspace."
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tc_cipher = { version = "0.1", path = "../tc_cipher" }
tc_crypto = { version = "0.1", path = "../tc_crypto" }
tc_ecb = { version = "0.1", path = "../block_modes/tc_ecb" }

[dev-dependencies]
tc_aes = { version = "0.1", path = "../block_cipher/tc_aes" }
tc_ascon_aead = { version = "0.1", path = "../aead_cipher/tc_ascon_aead" }
tc_ccm = { version = "0.1", path = "../aead_cipher/tc_ccm" }
tc_cfb = { version = "0.1", path = "../block_modes/tc_cfb" }
tc_params = { version = "0.1", path = "../tc_params" }
tc_rc4 = { version = "0.1", path = "../stream_cipher/tc_rc4" }
