[package]
name = "tc_des"
description = "Data Encryption Standard implementations for the tc_rust workspace."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tc_cipher = { version = "0.1", path = "../../tc_cipher" }
tc_crypto = { version = "0.1", path = "../../tc_crypto" }
tc_params = { version = "0.1", path = "../../tc_params" }
