//! SHA-512/t message digest (FIPS 180-4), ported from Bouncy Castle's
//! `Sha512tDigest`.
//!
//! SHA-512/t is SHA-512 with a truncated `t`-bit output and a *distinct* initial
//! hash value derived per `t` (so e.g. SHA-512/256 is not merely truncated
//! SHA-512). The IV is generated by running SHA-512 — with every IV word XORed
//! with `0xa5…a5` — over the ASCII string `"SHA-512/t"`. Reuses
//! [`sha512_core::compress`](crate::sha512_core::compress).

use core::convert::Infallible;

use alloc::string::String;

use tc_crypto_core::TryDigest;

use crate::md_buffer::MdBuffer;
use crate::sha512_core::{compress, IV as SHA512_IV};

const BYTE_LENGTH: usize = 128;
const A5: u64 = 0xa5a5_a5a5_a5a5_a5a5;

/// The SHA-512/t digest (FIPS 180-4), producing a `t/8`-byte hash.
#[derive(Clone)]
pub struct Sha512tDigest {
    /// 8 個 64-bit 鏈結暫存器。
    h: [u64; 8],
    /// 共用的 128-byte 區塊緩衝。
    buf: MdBuffer<128>,
    /// 依 `t` 生成的初始值(reset 時還原)。
    iv: [u64; 8],
    /// 輸出位元組數 = `t / 8`。
    digest_len: usize,
    /// 演算法名稱,如 `"SHA-512/256"`(依 `t` 而定)。
    name: String,
}

impl Sha512tDigest {
    /// Creates a SHA-512/`bit_length` digest.
    ///
    /// # Panics
    ///
    /// Panics (mirroring bc's `ArgumentException`) if `bit_length` is not a
    /// multiple of 8, is `>= 512`, or is `384` (use SHA-384 instead).
    pub fn new(bit_length: usize) -> Self {
        assert!(bit_length < 512, "SHA-512/t: bit length cannot be >= 512");
        assert!(
            bit_length % 8 == 0,
            "SHA-512/t: bit length must be a multiple of 8"
        );
        assert!(
            bit_length != 384,
            "SHA-512/t: cannot be 384 — use SHA-384 instead"
        );

        let iv = generate_iv(bit_length);
        Sha512tDigest {
            h: iv,
            buf: MdBuffer::new(),
            iv,
            digest_len: bit_length / 8,
            name: alloc::format!("SHA-512/{bit_length}"),
        }
    }
}

/// SHA-512/t 的 IV 生成(bc `tIvGenerate`):以 SHA-512 IV ⊕ A5 起始,對 ASCII
/// `"SHA-512/<t>"` 跑一次 SHA-512,輸出即為此 `t` 的 IV。
fn generate_iv(bit_length: usize) -> [u64; 8] {
    let mut h = SHA512_IV;
    for x in &mut h {
        *x ^= A5;
    }

    let mut buf = MdBuffer::<128>::new();
    buf.update(b"SHA-512/", |b| compress(&mut h, b));

    // bit_length 的十進位 ASCII(合法 t 為 8..=504,故 1..3 位)。
    let mut digits = [0u8; 3];
    let mut n = bit_length;
    let mut i = digits.len();
    loop {
        i -= 1;
        digits[i] = b'0' + (n % 10) as u8;
        n /= 10;
        if n == 0 {
            break;
        }
    }
    buf.update(&digits[i..], |b| compress(&mut h, b));

    let bit_len = (buf.byte_count() as u128) << 3;
    buf.finish(&bit_len.to_be_bytes(), |b| compress(&mut h, b));
    h
}

impl TryDigest for Sha512tDigest {
    type Error = Infallible; // 純計算,永不失敗 → 自動獲得 Digest

    fn algorithm_name(&self) -> &str {
        &self.name
    }

    /// 輸出長度 = `t / 8` bytes(依實例而定)。
    fn digest_size(&self) -> usize {
        self.digest_len
    }

    fn byte_length(&self) -> usize {
        BYTE_LENGTH
    }

    fn try_update(&mut self, input: &[u8]) -> Result<(), Self::Error> {
        let Self { h, buf, .. } = self;
        buf.update(input, |block| compress(h, block));
        Ok(())
    }

    fn try_do_final(&mut self, output: &mut [u8]) -> Result<usize, Self::Error> {
        let len = self.digest_len;
        {
            let Self { h, buf, .. } = self;
            let bit_len = (buf.byte_count() as u128) << 3;
            buf.finish(&bit_len.to_be_bytes(), |block| compress(h, block));
            // 先寫滿 64 bytes,再截斷到 t/8(t 為 8 的倍數,可能落在字中間)。
            let mut full = [0u8; 64];
            for (i, &word) in h.iter().enumerate() {
                full[i * 8..i * 8 + 8].copy_from_slice(&word.to_be_bytes());
            }
            output[..len].copy_from_slice(&full[..len]);
        }
        self.try_reset()?;
        Ok(len)
    }

    fn try_reset(&mut self) -> Result<(), Self::Error> {
        self.h = self.iv;
        self.buf.reset();
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use alloc::{format, string::String};

    use super::*;
    use tc_crypto_core::Digest;

    fn hex(d: &mut Sha512tDigest, input: &[u8]) -> String {
        d.update(input);
        let mut out = [0u8; 64];
        let n = d.do_final(&mut out);
        let mut s = String::with_capacity(n * 2);
        for &b in &out[..n] {
            s.push_str(&format!("{b:02x}"));
        }
        s
    }

    // NIST 的 SHA-512/224 與 SHA-512/256 已知向量。
    #[test]
    fn sha512_224_vectors() {
        let mut d = Sha512tDigest::new(224);
        assert_eq!(d.algorithm_name(), "SHA-512/224");
        assert_eq!(d.digest_size(), 28);
        assert_eq!(
            hex(&mut d, b""),
            "6ed0dd02806fa89e25de060c19d3ac86cabb87d6a0ddd05c333b84f4"
        );
        assert_eq!(
            hex(&mut d, b"abc"),
            "4634270f707b6a54daae7530460842e20e37ed265ceee9a43e8924aa"
        );
    }

    #[test]
    fn sha512_256_vectors() {
        let mut d = Sha512tDigest::new(256);
        assert_eq!(d.algorithm_name(), "SHA-512/256");
        assert_eq!(d.digest_size(), 32);
        assert_eq!(
            hex(&mut d, b""),
            "c672b8d1ef56ed28ab87c3622c5114069bdd3ad7b8f9737498d0c01ecef0967a"
        );
        assert_eq!(
            hex(&mut d, b"abc"),
            "53048e2681941ef99b2e29b76b4c7dabe4c2d0c634fc6d46e0e2f13107e7af23"
        );
    }

    #[test]
    #[should_panic]
    fn rejects_384() {
        let _ = Sha512tDigest::new(384);
    }

    #[test]
    #[should_panic]
    fn rejects_non_multiple_of_8() {
        let _ = Sha512tDigest::new(100);
    }
}
